### ISSUE TITLE
Webfiles - Note contents being removed - site stops working

### ISSUE THREAD

**Issue by bowrudder** [MscrmTools/MscrmTools.PortalRecordsMover#27]
Hi,
I use this to deploy a who website, and at the moment this version has stopped transferring successfully the webfiles completely.  

What does the new option to replace attachments do? when should it be used? and why is it removing all of the webfiles it previously copied successfully?

Regards
Tom

**Comment by bowrudder** [comment]
Hi, this is the error message in the log --> for all Webfiles

2019-11-25 11:41:47.350 AM		Error	 (Note/58472dde-25b3-e711-8107-70106faa5221): Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
2019-11-25 11:41:47.545 AM		Info	Record  updated (Note/23a53525-2bb3-e711-8107-70106faa5221)

**Comment by MscrmTools** [comment]
I'm not sure to understand the real issue here.

When importing web files, you are asked if you want to clean web files annotations. Why that? Some users are deleting the note and creating a new one in the web file, leading to a different id. And then to two (or more) notes associated to the web file record.

When importing web files, Portal Records Mover, if you allow it, delete all notes from the web file EXCEPT the one it just created [See code](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/blob/master/MscrmTools.PortalRecordsMover/AppCode/RecordManager.cs#L224)

In any case, it should not delete all annotations from the web file.

**Comment by bowrudder** [comment]
Hi the issue is that with this release, the files are no longer being written to the target.  It does not matter whether I choose "Yes" or "No", the file created seems not to exist - or is an incorrect format / not recognised.  So that when the website looks for the file it gives "404" file not found.

We used another utility in XRM toolbox to just move the WebFiles - and it worked.

[MscrmTools.PortalRecordsMover.txt](https://github.com/MscrmTools/MscrmTools.PortalRecordsMover/files/3896856/MscrmTools.PortalRecordsMover.txt)

**Comment by MscrmTools** [comment]
I found an issue that lead to all these errors in the log file.
Nevertheless, the annotation is updated BEFORE this issue. I just made a test and the annotation was updated correctly.
I will continue to investigate anyway

**Comment by MscrmTools** [comment]
Closing this issue for now. If it's still an existing problem, please comment
