### ISSUE TITLE
Error on exporting active reocrds only

### ISSUE THREAD

**Issue by aboodh95** [MscrmTools/MscrmTools.PortalRecordsMover#5]
Hi 

once i'm checking the option to get the Active records only i'm getting this message because of Note entity
![image](https://user-images.githubusercontent.com/12459798/34339499-4eabe618-e98e-11e7-936b-374e3f909e1c.png)

**Comment by MscrmTools** [comment]
What is the error?

**Comment by aboodh95** [comment]
You cannot see the image?
the error is:
An error occurred: 'Annotation' entity doesn't contain attribute with name = 'statecode'

**Comment by MscrmTools** [comment]
Are you sure you use the latest version?

**Comment by aboodh95** [comment]
![image](https://user-images.githubusercontent.com/12459798/34341954-0dd561e0-e9bc-11e7-877e-50d7a03a9ea0.png)

1.2017.7.3

**Comment by Ale-Cesetti** [comment]
Hi, I am experiencing the same. In order to reproduce this Tanguy, you have to select the note entity, check the Get only active records and click Retrieve records.

This can be fixed in line 519 of file MscrmTools.PortalRecordsMover\MyPluginControl.cs. I would add a condition to the if asking for entity name and if annotation don't include the query criteria for statecode.

I hope this helps.

**Comment by Ale-Cesetti** [comment]
@MscrmTools I have updated the code, if you want I can commit it.

![image](https://user-images.githubusercontent.com/15171286/34391107-ab80af32-eb22-11e7-8668-291ebcf3ee6c.png)
